name: Notify Release
description: 'Notify on google chat'

inputs:
  google-chat-webhook:
    description: 'Google chat webhook'
    required: true

  image:
    description: 'Logo url '
    required: true

  title:
    description: 'Message title'
    required: true
    default: '{App Name}'

  subtitle:
    description: 'Message subtitle'
    required: true
    default: '{Message Info}'

  app-link:
    description: 'App download link'
    required: true
    default: ''

  app-version:
    description: 'App version name'
    required: true
    default: '1.0'

  skip-tag:
    description: 'Skip GitHub tag from release note'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Retrieve release note
      id: release-note
      shell: bash
      run: |
        {
            echo 'RELEASE_NOTE<<EOF'
            git log -1 --format=%B
            echo EOF
        } >> "$GITHUB_ENV"

    - name: Notify on google chat
      shell: bash
      run: |
        if ${{ env.SKIP_TAG == false || env.SKIP_TAG == 'false' }}; then
          java -jar .github/google-chat-client.jar --url '${{ env.GOOGLE_CHAT_WEBHOOK }}' --title '${{ env.ACTION_TITLE }}' --subtitle '${{ env.ACTION_SUBTITLE }}' --imageUrl '${{ env.ACTION_LOGO }}' --desc '${{ env.ACTION_DESCRIPTION }}' --action '${{ env.DOWNLOAD_ACTION }}' --actionUrl '${{ env.DOWNLOAD_URL }}' --action '${{ env.TAG_ACTION }}' --actionUrl '${{ env.TAG_URL }}'
        else 
          java -jar .github/google-chat-client.jar --url '${{ env.GOOGLE_CHAT_WEBHOOK }}' --title '${{ env.ACTION_TITLE }}' --subtitle '${{ env.ACTION_SUBTITLE }}' --imageUrl '${{ env.ACTION_LOGO }}' --desc '${{ env.ACTION_DESCRIPTION }}' --action '${{ env.DOWNLOAD_ACTION }}' --actionUrl '${{ env.DOWNLOAD_URL }}'
        fi
      env:
        GOOGLE_CHAT_WEBHOOK: ${{ inputs.google-chat-webhook }}
        ACTION_LOGO: ${{ inputs.image }}
        ACTION_TITLE: ${{ inputs.title }}
        ACTION_SUBTITLE: ${{ inputs.subtitle }}
        ACTION_DESCRIPTION: "<b>Release Note:</b><br>${{ env.RELEASE_NOTE }}"
        DOWNLOAD_ACTION: "Download"
        DOWNLOAD_URL: ${{ inputs.app-link }}
        TAG_ACTION: ${{ inputs.app-version }}
        TAG_URL: "${{ github.server_url }}/${{ github.repository }}/releases/tag/v${{ inputs.app-version }}"
