# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Perform a PR check"
  lane :pr_check do
    gradle(task: "clean build")
  end

  desc "Deploy staging build to Firebase Distribution"
  lane :staging do
    gradle(task: "clean assembleStagingRelease")

    firebase_app_distribution(
        app: ENV["FIREBASE_APP_ID"],
        service_credentials_file: ENV["SERVICE_ACCOUNT_FILE"],
        groups: ENV["FIREBASE_TESTER_GROUPS"],
        release_notes: sh("git log -1 --format=%s"),
        android_artifact_type: "apk",
        android_artifact_path: ENV["ANDROID_ARTIFACT_PATH"]
    )
  end

  desc "Deploy production build to Firebase Distribution"
  lane :production do
    gradle(task: "clean assembleProductionRelease")

  end
end
