name: Deploy Develop Build

on:
  workflow_dispatch:
    inputs:
      deploy_android:
        description: 'Deploy Android App'
        required: true
        default: 'yes'
        type: choice
        options:
          - yes
          - no
  push:
    branches: [ 'develop' ]

permissions:
  actions: write
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GOOGLE_SERVICES_FILE_NAME: "google-services.json"
  APP_NAME: "Hopdoc - Android"
  FIREBASE_DISTRIBUTION_LINK: "https://appdistribution.firebase.google.com/testerapps"

jobs:
  build-android:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: ${{ inputs.deploy_android == 'yes' || s.deploy_android == 'true' }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Retrieve version name
        shell: bash
        run: |
          echo "RELEASE_NAME=$(git log -1 --format=%s)" >> $GITHUB_ENV
          echo "VERSION_NAME=2.0.2" >> $GITHUB_ENV

      - name: Notify release on google chat
        uses: ./.github/actions/notify-google-chat
        with:
          google-chat-webhook: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          image: ${{ vars.HOPDOC_APP_LOGO }}
          title: ${{ env.APP_NAME }}
          subtitle: "v${{ env.VERSION_NAME }} is deployed on Firebase"
          app-link: '${{ env.FIREBASE_DISTRIBUTION_LINK }}/${{ secrets.FIREBASE_APP_ID }}'
          tag-name: "v${{ env.VERSION_NAME }} Tag"
