name: Deploy Staging Build

on:
  push:
    branches: [ 'release/**' ]

permissions:
  actions: write
  contents: write

env:
  GOOGLE_SERVICES_FILE_NAME: "google-services.json"

jobs:
  build-android:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Setup Environment
        run: echo ${{ secrets.SERVICE_ACCOUNT_FILE }} | base64 -d > ${{ env.GOOGLE_SERVICES_FILE_NAME }}

      - name: Build staging APK
        run: bundle exec fastlane staging
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          SERVICE_ACCOUNT_FILE: ${{ env.GOOGLE_SERVICES_FILE_NAME }}
          FIREBASE_TESTER_GROUPS: "kernelequity"

  create-tag:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: [firebase-distribution]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set tag version
        run: echo "VERSION_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Create tag
        uses: actions/github-script@v7
        id: create-tag
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v${{env.VERSION_NAME}}',
              sha: context.sha
            })